Add Garage
JorjKolton/NixAl pull request #5
Opened 2022-07-24 09:17 UTC by JorjKolton

Add Comparators

2022-07-24 09:21 UTC, JorjKolton commented
![](https://github.trello.services/images/mini-trello-icon.png) [Collections 1](https://trello.com/c/y6qVfJzs/59-collections-1)

2022-07-24 22:03 UTC, Fabolo12 requested changes

2022-07-24 22:03 UTC, Fabolo12 commented on src/main/java/com/nixal/ssobchenko/Main.java
> +        buses.sort(new Bus.PriceComparator().reversed());
Сортировка должна была быть по трек критериям

2022-07-25 22:53 UTC, Fabolo12 approved these changes

2022-07-26 11:06 UTC, merged