Add Builder pattern and SOLID
JorjKolton/NixAl pull request #9
Opened 2022-08-11 18:49 UTC by JorjKolton

2022-08-11 18:52 UTC, JorjKolton commented
![](https://github.trello.services/images/mini-trello-icon.png) [SOLID](https://trello.com/c/BPfVBwQs/114-solid)

2022-08-11 21:56 UTC, Fabolo12 requested changes
Не увидел СОЛИД проекта

2022-08-13 11:20 UTC, Fabolo12 approved these changes

2022-08-13 11:20 UTC, Fabolo12 commented on src/SOLID/src/main/java/com/example/model/product/Product.java
> +    public String getBasicInfo() {
Это костыль над toString

2022-08-13 11:20 UTC, Fabolo12 commented on src/SOLID/src/main/java/com/example/util/ProductUtils.java
> +            if (product.getClass().equals(NotifiableProduct.class)) {
Обычно проверка класса - показатель ошибки архитектуры

2022-08-13 16:27 UTC, merged